### ISSUE TITLE
Failed to install Npcap service 0x0004a020 

### ISSUE THREAD

**Issue by Kinny092** [nmap/npcap#267]
Hi,

I am trying to installed a test VM which is running Server 2012 r2 Datacenter 6.3.9600 Build 9600. It is intentionally unpatched for pentesting. Any help is much appreciated. Thanks

`PS C:\Users\Administrator> Get-AuthenticodeSignature "C:\Program Files\Npcap\npcap.cat" | select *

SignerCertificate      : [Subject]
                           CN=Insecure.Com LLC, O=Insecure.Com LLC, L=Seattle, S=Washington, C=US,
                         SERIALNUMBER=200010310013, OID.2.5.4.15=Private Organization,
                         OID.1.3.6.1.4.1.311.60.2.1.2=California, OID.1.3.6.1.4.1.311.60.2.1.3=US

                         [Issuer]
                           CN=DigiCert EV Code Signing CA (SHA2), OU=www.digicert.com, O=DigiCert Inc, C=US

                         [Serial Number]
                           09256314069E7E6A88CB823075C0D9C9

                         [Not Before]
                           1/05/2020 9:30:00 AM

                         [Not After]
                           7/05/2021 9:30:00 PM

                         [Thumbprint]
                           4CE89794FE2D2F7E30121F10BCF76AC3CCF77CA9

TimeStamperCertificate : [Subject]
                           CN=TIMESTAMP-SHA256-2019-10-15, O="DigiCert, Inc.", C=US

                         [Issuer]
                           CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US

                         [Serial Number]
                           04CD3F8568AE76C61BB0FE7160CCA76D

                         [Not Before]
                           1/10/2019 9:30:00 AM

                         [Not After]
                           17/10/2030 10:30:00 AM

                         [Thumbprint]
                           0325BD505EDA96302DC22F4FA01E4C28BE2834C5

Status                 : Valid
StatusMessage          : Signature verified.
Path                   : C:\Program Files\Npcap\npcap.cat

PS C:\Users\Administrator> Get-AuthenticodeSignature "C:\Program Files\Npcap\npcap.sys" | select *

SignerCertificate      : [Subject]
                           CN=Insecure.Com LLC, O=Insecure.Com LLC, L=Seattle, S=Washington, C=US,
                         SERIALNUMBER=200010310013, OID.2.5.4.15=Private Organization,
                         OID.1.3.6.1.4.1.311.60.2.1.2=California, OID.1.3.6.1.4.1.311.60.2.1.3=US

                         [Issuer]
                           CN=DigiCert EV Code Signing CA (SHA2), OU=www.digicert.com, O=DigiCert Inc, C=US

                         [Serial Number]
                           09256314069E7E6A88CB823075C0D9C9

                         [Not Before]
                           1/05/2020 9:30:00 AM

                         [Not After]
                           7/05/2021 9:30:00 PM

                         [Thumbprint]
                           4CE89794FE2D2F7E30121F10BCF76AC3CCF77CA9

TimeStamperCertificate : [Subject]
                           CN=TIMESTAMP-SHA256-2019-10-15, O="DigiCert, Inc.", C=US

                         [Issuer]
                           CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US

                         [Serial Number]
                           04CD3F8568AE76C61BB0FE7160CCA76D

                         [Not Before]
                           1/10/2019 9:30:00 AM

                         [Not After]
                           17/10/2030 10:30:00 AM

                         [Thumbprint]
                           0325BD505EDA96302DC22F4FA01E4C28BE2834C5

Status                 : Valid
StatusMessage          : Signature verified.
Path                   : C:\Program Files\Npcap\npcap.sys`

**Comment by emikg777** [comment]
Please, look here. I published solution for Windows 7, I think on Windows server 2012 it can work( https://github.com/nmap/npcap/issues/224 )

**Comment by 150d** [comment]
I'm seeing the same error on Windows Server 2012 with npcap v1.0 and v1.1.

The signature checks are both "valid" on my machine as well.

The GPOs mentioned in issue #224 are all "undefined". I even set them to "disabled" to make sure, but it didn't change the error.

**Comment by emikg777** [comment]
@150d Please look all discuss in [](https://github.com/nmap/npcap/issues/224) (especially [my second comment](https://github.com/nmap/npcap/issues/224#issuecomment-681906420)). For resolve this problem you must several action not only change GPO

**Comment by 150d** [comment]
@emikg777 Thanks for your help, but that's exactly my point: It didn't work.

- I'm trying to install npcap v1.10, which apparently should have fixes for this problem.
- "pnputil -e" doesn't show any npcap-related OEM files.
- All of the mentioned policies are set to "disabled".
- Reboot(s) didn't help.

Jet, it still doesn't work. Installation always stops at driver creation and rolls back subsequently.

Regards

**Comment by dmiller-nmap** [comment]
Consolidating this error as duplicate of #224
