### ISSUE TITLE
Wireshark is not able to see ethernet adapters after changing from WinPCAP to NPCAP on Windows server 2016 

### ISSUE THREAD

**Issue by pc500** [nmap/npcap#34]
Wireshark is not able to see ethernet adapters after changing from WinPCAP to NPCAP on Windows server 2016 for Broadcom Netextreme Virtual Function ethernet adapter.

Attached is the Diagreport.  I can reproduce on a fresh empty VM and provide remote access if desired.

C:\Program Files\Wireshark>dumpcap.exe -D
1. \Device\NPF_Loopback (Adapter for loopback traffic capture)

C:\Program Files\Wireshark>

*************************************************
Network Adapter(s) Info:
*************************************************

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Ethernet                  Broadcom NetXtreme-E Virtual Function         3 Up           00-00-17-02-79-0E        25 Gbps

Caption         : [00000002] Broadcom NetXtreme-E Virtual Function
GUID            : {CC75C87B-6F35-4560-8556-EA0329DA6CB7}
Index           : 2
InterfaceIndex  : 3
Manufacturer    : Broadcom Corporation
NetConnectionID : Ethernet
PNPDeviceID     : PCI\VEN_14E4&DEV_16DC&SUBSYS_16D7108E&REV_00\3&13C0B0C5&1&18
[diagreport.txt](https://github.com/nmap/nmap/files/4113892/diagreport.txt)

**Comment by pc500** [comment]
Thank you for your continued effort to look into this.

If at any point in the development cycle you need any resources, such as a Virtual Machine to reproduce and test this on, please reach out and I can provide this for you.

**Comment by fyodor** [comment]
For the purpose of prioritization, I'm just noting that we had a customer recently request Virtual Function driver support on behalf of one of their customers who was using the technology.

**Comment by dmiller-nmap** [comment]
This issue should be resolved in Npcap 1.80, but we would appreciate if someone with the Broadcom NetXtreme adapter could confirm.

**Comment by pc500** [comment]
> This issue should be resolved in Npcap 1.80, but we would appreciate if someone with the Broadcom NetXtreme adapter could confirm.

We are validating this, and will reply shortly.

**Comment by nodeez** [comment]
On behalf of @pc500 - Confirmed, updated version (1.80) does work. 

Using Wireshark 4.4.0 and npcap 1.80:

C:\Program Files\Wireshark>dumpcap.exe -D
1. \Device\NPF_{D99F48E6-1815-4F12-80C4-DB764D7B456F} (Ethernet 3)
2. \Device\NPF_Loopback (Adapter for loopback traffic capture)

From C:\Program Files\Npcap>diagreport.bat:

*************************************************
Network Adapter(s) Info:
*************************************************
Caption             : [00000005] Broadcom NetXtreme-E Virtual Function
GUID                : {D99F48E6-1815-4F12-80C4-DB764D7B456F}
Index               : 5
InterfaceIndex      : 7
Manufacturer        : Broadcom Corporation
MACAddress          : 02:00:17:30:29:95
Speed               : 25000000000
NetConnectionID     : Ethernet 3
NetConnectionStatus : 2
PNPDeviceID         : PCI\VEN_14E4&DEV_16DC&SUBSYS_16D7108E&REV_00\3&267A616A&1&18
ServiceName         : bnxtnd
AdapterType         : Ethernet 802.3

For completeness, install steps were: 
Install npcap1.80 first
Install Wireshark 4.4.0 second, enable "winpcap api compatibility"

**Comment by nodeez** [comment]
@dmiller-nmap, we still have a vm to test with. Would you like to take a look at the VM? Or are you good to go?

**Comment by dmiller-nmap** [comment]
@nodeez @pc500 Thanks so much for confirming! We'll consider this issue closed.

**Comment by pada1874** [comment]
[`877987898779`](url)
